//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class SpriteCollection
{
	private Sprite[] sprites;
	private string[] names;
	
	public SpriteCollection(string spritesheet)
	{
		//try {
			sprites = Resources.LoadAll<Sprite>(spritesheet);
			names = new string[sprites.Length];


		
			for(var i = 0; i < names.Length; i++)
			{
				names[i] = sprites[i].name;
			}
		//} catch (ArgumentException) {}
	}
	
	public Sprite GetSprite(string name)
	{
		//try {
		return sprites[System.Array.IndexOf(names, name)];
		//} catch (ArgumentNullException) {}
		//return null;
	}
}

